[application]
app = "frontend/fro"
default_platform = "web"
asset_dir = "frontend/fro/public"
out_dir = "frontend/fro/dist"

[web.watcher]
watch_path = ["frontend/fro/src", "frontend/fro/public", "frontend/fro/assets"]
reload_html = true
index_on_404 = true

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []

[web.wasm_opt]
level = "z"

[web.asset_compression]
gzip = true
brotli = true

[web.resource.inline]
scripts = true
styles = true

