/// Enumeration of all help topics available in the hardware configuration page.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HelpTopic {
    Backend,
    Model,
    NumThread,
    NumGpu,
    GpuLayers,
    MainGpu,
    RopeBase,
    RopeScale,
    LowVram,
    F16Kv,
    NumBatch,
    NumCtx,
    Numa,
    Mmap,
    Mlock,
    LogitsAll,
    VocabOnly,
    Reload,
    RopeTuning,
    // Sampling parameters
    Temperature,
    TopK,
    TopP,
    MinP,
    TypicalP,
    TfsZ,
    Seed,
    // Repetition control
    RepeatLastN,
    RepeatPenalty,
    PresencePenalty,
    FrequencyPenalty,
    PenalizeNewline,
    // Mirostat (adaptive sampling)
    Mirostat,
    MirostatTau,
    MirostatEta,
    // Output control
    NumPredict,
    NumKeep,
    StopSequences,
    // Quantization
    Quantization,

    // Llama.cpp / local-backend specifics (hardware page fields)
    SplitMode,
    NumUBatch,
    NumSeqMax,
    FlashAttn,
    OffloadKqv,
    Embeddings,
    NumThreadBatch,
    CpuStrict,
    Poll,
    Priority,
    IgnoreEos,
    // Tile-level overview
    SamplingParams,
    // DRY sampling
    DryMultiplier,
    DryBase,
    DryAllowedLen,
    // XTC sampling
    XtcProbability,
    XtcThreshold,
}

impl HelpTopic {
    /// Returns the title for this help topic.
    pub fn title(&self) -> &'static str {
        match self {
            Self::Backend => "Inference backend",
            Self::Model => "Model selection",
            Self::NumThread => "num_thread",
            Self::NumGpu => "num_gpu",
            Self::GpuLayers => "gpu_layers",
            Self::MainGpu => "main_gpu",
            Self::RopeBase => "RoPE base frequency",
            Self::RopeScale => "RoPE scale",
            Self::LowVram => "low_vram",
            Self::F16Kv => "f16_kv",
            Self::NumBatch => "num_batch",
            Self::NumCtx => "num_ctx",
            Self::Numa => "NUMA",
            Self::Mmap => "use_mmap",
            Self::Mlock => "use_mlock",
            Self::LogitsAll => "logits_all",
            Self::VocabOnly => "vocab_only",
            Self::Reload => "Reload Models",
            Self::RopeTuning => "RoPE Tuning",
            Self::Temperature => "Temperature",
            Self::TopK => "Top-K",
            Self::TopP => "Top-P (Nucleus Sampling)",
            Self::MinP => "Min-P",
            Self::TypicalP => "Typical-P",
            Self::TfsZ => "Tail Free Sampling (TFS)",
            Self::Seed => "Seed",
            Self::RepeatLastN => "Repeat Last N",
            Self::RepeatPenalty => "Repeat Penalty",
            Self::PresencePenalty => "Presence Penalty",
            Self::FrequencyPenalty => "Frequency Penalty",
            Self::PenalizeNewline => "Penalize Newline",
            Self::Mirostat => "Mirostat Mode",
            Self::MirostatTau => "Mirostat Tau (Target Entropy)",
            Self::MirostatEta => "Mirostat Eta (Learning Rate)",
            Self::NumPredict => "Max Tokens (num_predict)",
            Self::NumKeep => "Tokens to Keep (num_keep)",
            Self::StopSequences => "Stop Sequences",
            Self::Quantization => "Quantization Guide",

            Self::SplitMode => "split_mode",
            Self::NumUBatch => "num_ubatch",
            Self::NumSeqMax => "num_seq_max",
            Self::FlashAttn => "flash_attn",
            Self::OffloadKqv => "offload_kqv",
            Self::Embeddings => "embeddings",
            Self::NumThreadBatch => "num_thread_batch",
            Self::CpuStrict => "cpu_strict",
            Self::Poll => "poll",
            Self::Priority => "priority",
            Self::IgnoreEos => "ignore_eos",
            Self::SamplingParams => "Sampling Params",
            Self::DryMultiplier => "dry_multiplier",
            Self::DryBase => "dry_base",
            Self::DryAllowedLen => "dry_allowed_length",
            Self::XtcProbability => "xtc_probability",
            Self::XtcThreshold => "xtc_threshold",
        }
    }

    /// Returns the help paragraphs for this topic.
    pub fn paragraphs(&self) -> Vec<&'static str> {
        match self {
            Self::Backend => vec![
                "Select the runtime that executes prompts (local llama.cpp, Ollama, vLLM, OpenAI, etc.).",
                "Switching backend clears the model name so you can pick a compatible artifact.",
                "",
                "Ollama",
                "Ollama is a model server. It runs as an empty process \u{2014} no model loaded at startup. When a request arrives with e.g. `\"model\": \"phi:latest\"`, Ollama checks if that model is already in memory. If not, it loads it from its own model store (`~/.ollama/models/`). If a different model was loaded, it evicts the old one (after ~5 min idle) and loads the new one.",
                "The model selection happens at request time, driven by the API call, not at startup. That\u{2019}s why the systemd service file just says `ollama serve` \u{2014} no model path needed.",
                "",
                "llama-server (llama.cpp)",
                "llama-server is a single-model server. At startup, it reads the `--model /path/to/file.gguf` flag, loads that one model into memory, and serves only that model for its entire lifetime.",
                "To switch models, you must stop the process, change the `--model` argument, and restart. There\u{2019}s no API to swap models at runtime.",
                "",
                "What this means in the UI",
                "Ollama: changing the model dropdown just changes which model name gets sent in API requests \u{2014} no restart needed.",
                "llama-server: changing the model means rewriting the env file and restarting the llama-server service \u{2014} a heavier operation with a brief downtime.",
            ],
            Self::Model => vec![
                "When the backend exposes a discovery API the select menu lists its models.",
                "You can always type a model identifier manually, e.g., `llama3:8b`.",
                "Any .gguf/.bin files under ~/.local/share/ag/models/ (or $AG_HOME/models/) appear automatically.",
                "Custom entries are labeled \"(custom)\" and, if `CUSTOM_MODEL_ENABLED=true` plus `CUSTOM_MODEL_NAME` matches, you will see a `• active` tag in both the dropdown and the read-only Active model field.",
                "If the backend is set to a local runner such as Ollama, the custom list is merged with /sys/models so you can manage everything from one place.",
                "To try it: run installer/custom_model.sh, ensure it appends CUSTOM_MODEL_* env vars to ~/.config/ag/env, then reload the model list to see the detected custom model badge.",
            ],
            Self::NumThread => vec![
                "Sets the number of threads used for inference computation by the underlying llama.cpp backend—specifically for the CPU-bound matrix operations during token generation.",
                "Main thread        → coordinates, spawns others",
                "Worker threads     → general task execution",
                "Blocking threads   → isolated sync work",
                "I/O threads        → poll for I/O completion",
                "Timer thread       → fires scheduled callbacks",
                "\"Worker\" is just the role of \"executes tasks from a queue.\" It's the generic grunt work, which is why thread pools are often called \"worker pools.\"",
                "Match physical cores for best throughput; higher values may hurt latency.",
                "If you're running other CPU-intensive work alongside (like embedding generation, reranking, or heavy document processing), setting num_thread to something like physical_cores - 2 can improve overall system responsiveness without dramatically hurting inference speed.",
            ],
            Self::NumGpu => vec![
                "Number of GPU devices to employ.",
                "Set to 0 to keep all inference on CPU even if GPUs are detected.",
            ],
            Self::GpuLayers => vec![
                "How many transformer layers to offload to GPU memory.",
                "Increasing the value speeds up inference until you exhaust VRAM.",
            ],
            Self::MainGpu => vec![
                "Select which GPU index hosts the embeddings cache and KV store.",
                "Set 0 unless you want to pin workloads to a different adapter.",
            ],
            Self::RopeBase => vec![
                "rope_freq_base determines how quickly RoPE's rotational angles grow with token position, and adjusting it changes how far a model can stretch its context window before attention becomes unstable. A higher value compresses positional information so the model can operate over longer sequences, but too much compression harms short‑range accuracy and overall coherence. Finding the best target context and the best context length is therefore a balancing act between long‑range stability and short‑range precision.",
                "",
                "How rope_freq_base shapes the usable context",
                "RoPE encodes position by rotating the query (Q) and key (K) vectors in 2‑D subspaces. The rotation angle for position (p) is:",
                "θ(p) = p · ω",
                "where ω is derived from rope_freq_base. Changing rope_freq_base changes how steeply θ grows:",
                "• Higher rope_freq_base → smaller ω — slower rotation, compressed positions, longer usable context.",
                "• Lower rope_freq_base → larger ω — faster rotation, expanded positions, shorter effective context.",
                "This is the mechanism behind context‑extension techniques in llama.cpp.",
                "",
                "Why too much compression breaks quality",
                "When rope_freq_base is pushed too high, the model's learned positional geometry becomes distorted. The most common symptoms are:",
                "• mixing up nearby tokens or losing track of local structure",
                "• degraded coding, math, or reasoning performance",
                "• attention drifting to irrelevant earlier text",
                "• loss of coherence before reaching the intended extended context",
                "These failures appear because the model was trained with a specific frequency distribution and cannot generalize indefinitely when the positional signal is compressed too aggressively.",
                "",
                "How to find the best target context",
                "The target context is the maximum length you want the model to handle. Choosing it depends on your use case:",
                "• Long‑form reading or summarization benefits from larger targets (e.g., 16k–32k).",
                "• Coding, math, and reasoning benefit from smaller targets (e.g., 8k–12k).",
                "• Chat‑style interaction usually works well with moderate targets (e.g., 8k–16k).",
                "A good target is the smallest context that reliably covers your real workload. Overshooting the target forces unnecessary compression and reduces quality.",
                "",
                "How to find the best usable context length",
                "The usable context length is the longest sequence where the model remains stable after adjusting rope_freq_base. A practical evaluation process includes several complementary checks:",
                "1. Test retrieval at increasing distances:",
                "   Feed the model a document and ask questions about earlier sections at different distances (e.g., 4k, 8k, 12k, 16k tokens). The best context length is the longest distance where:",
                "   • the model retrieves earlier information correctly",
                "   • answers remain consistent",
                "   • no sudden drop in coherence occurs",
                "2. Check short‑range reasoning:",
                "   After adjusting rope_freq_base, run short tasks such as step‑by‑step math, code generation, and instruction following. If these degrade noticeably, the positional compression is too strong.",
                "3. Evaluate long‑form generation:",
                "   Generate multi‑page text and look for drifting topics, repeated sections, contradictions, or sudden loss of structure. These are early signs that the context window is beyond the model's stable range.",
                "4. Respect the model's native RoPE settings:",
                "   Some models (e.g., CodeLlama) use custom RoPE frequencies. Overriding them too aggressively causes immediate quality loss. The best context window must be found relative to the model's original design.",
                "5. Observe attention stability:",
                "   If the model begins to \"forget\" or mis-locate earlier tokens, the context window is too large. This is a reliable indicator that the chosen rope_freq_base is compressing too much.",
                "",
                "Practical rule of thumb",
                "A balanced approach is:",
                "• Increase rope_freq_base only enough to reach your target context.",
                "• Validate both long‑range retrieval and short‑range reasoning.",
                "• Reduce the value if short‑range quality drops or if coherence collapses before the target length.",
                "This method aligns with how practitioners tune RoPE scaling in llama.cpp and similar frameworks.",
            ],
            Self::RopeScale => vec![
                "rope_freq_scale is a second RoPE‑related parameter in llama.cpp that controls how strongly the RoPE frequencies are scaled. While rope_freq_base sets the starting frequency, rope_freq_scale multiplies or stretches the entire frequency curve. Together, they determine how fast or slow the Q/K rotation angles grow with token position, which directly affects how far the model can extend its context window.",
                "",
                "What rope_freq_scale actually does",
                "RoPE uses a set of frequencies to rotate the query (Q) and key (K) vectors. These frequencies normally follow a fixed geometric progression. rope_freq_scale multiplies all of them by a constant factor.",
                "• A smaller rope_freq_scale (e.g., 0.5 or 0.125) slows down the rotation → positions are compressed → longer usable context.",
                "• A larger rope_freq_scale speeds up the rotation → positions spread out → shorter effective context.",
                "This parameter is often used in extended‑context models. Some models require specific values, and using the wrong one can break output quality.",
                "",
                "Why rope_freq_scale matters",
                "RoPE rotations encode positional information. If the rotation angle grows too quickly, the model \"runs out of space\" and loses positional coherence beyond its trained context. If the angle grows too slowly, the model loses fine-grained positional detail.",
                "rope_freq_scale adjusts this growth rate without changing the base frequency structure.",
                "This is especially important in long‑context models. Some extended‑context GGUF files include their own scaling parameters, and llama.cpp can read them automatically. But users sometimes still need to set rope_freq_scale manually to get sensible output.",
                "",
                "How rope_freq_scale interacts with rope_freq_base",
                "Both parameters affect the same underlying mechanism but in different ways:",
                "• rope_freq_base changes the starting point of the frequency curve.",
                "• rope_freq_scale stretches or compresses the entire curve.",
                "Together, they determine how the model perceives positional distance.",
                "",
                "How to find the best target context length",
                "The best target context length is the longest sequence where the model remains stable after adjusting RoPE parameters. Because every model is trained with different RoPE settings, the optimal context length must be discovered experimentally.",
                "1. Start from the model's native context:",
                "   Check the GGUF metadata. Many extended‑context models already include tuned RoPE scaling. Using the wrong rope_freq_scale overrides these values and can degrade quality.",
                "2. Increase context gradually:",
                "   Test at steps such as 4k → 8k → 12k → 16k → 24k → 32k.",
                "   At each step, evaluate whether the model retrieves earlier information correctly, coherence remains stable, and it avoids drifting or repeating.",
                "3. Run short‑range reasoning tests:",
                "   After adjusting rope_freq_scale, test coding tasks, math reasoning, and instruction following. If these degrade, the scaling is too aggressive.",
                "4. Watch for early breakdown:",
                "   If the model collapses (e.g., outputs only spaces or newlines), this is a strong sign that rope_freq_scale is incorrect for that model.",
                "5. Use community‑tested scaling laws:",
                "   Long‑context research shows that moderate scaling preserves quality, while extreme scaling causes attention instability. Techniques like NTK‑aware scaling and YaRN scaling were developed to avoid these issues.",
                "",
                "Practical rule of thumb",
                "• Use the model's built‑in RoPE parameters whenever possible.",
                "• If extending context manually, adjust rope_freq_scale slowly and test both long‑range retrieval and short‑range reasoning.",
                "• Stop increasing context when either long‑range retrieval fails or short‑range reasoning degrades. That balance point is your best target context length.",
            ],
            Self::LowVram => vec![
                "Enables llama.cpp optimizations that reduce peak VRAM usage.",
                "Disabling may improve latency when ample VRAM is available.",
            ],
            Self::F16Kv => vec![
                "Store the KV cache in fp16 instead of fp32 to save memory.",
                "Turn off only when debugging precision-sensitive workloads.",
            ],
            Self::NumBatch => vec![
                "Controls how many tokens are processed per batch on decode steps.",
                "Higher values increase throughput but consume additional RAM/VRAM.",
            ],
            Self::NumCtx => vec![
                "Maximum context window size in tokens.",
                "For llama-server (llama.cpp): this is a startup flag, not a runtime parameter. llama-server does not accept a per-request context override via its OpenAI-compatible API. The value here is reflected in the startup command shown on this page — copy that command and restart llama-server to change it.",
                "For Ollama: this value is sent as options.num_ctx on every request, so Ollama honours it without a restart.",
                "Larger values allow longer conversations but increase KV-cache memory proportionally. A 32k context uses roughly 16× more KV memory than a 2048 context for the same model.",
            ],
            Self::Numa => vec![
                "NUMA is a memory architecture design used in multi-processor systems where memory access time depends on the memory location relative to the processor.",
                "Each CPU has its own 'local' memory that it can access quickly. CPUs can also access other CPUs' 'remote' memory, but it's slower. This contrasts with UMA (Uniform Memory Access) where all memory has equal access time.",
                "As systems added more CPUs, a single memory bus became a bottleneck. NUMA lets each processor have a fast path to its own memory bank, improving overall throughput at the cost of non-uniform latency.",
                "Operating systems try to allocate memory local to the CPU running a process. Performance-sensitive applications like databases and VMs often need NUMA-aware configuration.",
                "On Linux you can check NUMA topology with `numactl --hardware` or `lscpu`. On Windows, open Task Manager, go to Performance, then CPU, right-click the graph and select 'Change graph to NUMA nodes'. You can also use PowerShell with `Get-CimInstance Win32_Processor | Select-Object SocketDesignation,NumberOfCores` or the Sysinternals tool Coreinfo with `coreinfo -n`.",
                "Most consumer desktop systems are UMA — NUMA mainly matters for multi-socket servers.",
            ],
            Self::Mmap => vec![
                "Memory-map model files instead of loading them entirely into RAM.",
                "Reduces initial load time and memory usage for large models.",
            ],
            Self::Mlock => vec![
                "Lock model weights in RAM to prevent swapping to disk.",
                "Improves inference latency but requires sufficient available memory.",
            ],
            Self::LogitsAll => vec![
                "When logits_all is enabled, the model returns the raw logit scores (unnormalized probabilities) for every token position in the input sequence, not just the final token.",
                "Normal mode (logits_all = off): The model only returns logits for the last token position. This is sufficient for standard text generation where you only need to predict what comes next.",
                "logits_all = on: The model returns a full matrix of logits — for each position in your input, you get scores for the entire vocabulary. If your input has 100 tokens and the vocabulary is 32,000 tokens, you get 100 × 32,000 = 3.2 million values.",
                "Consequences: Memory usage increases significantly — you're storing logits for every position instead of just one. Inference may be slightly slower due to the extra data being computed and transferred. Required for perplexity calculation — you need to know how probable each actual token was at each position. Useful for analysis tasks like understanding what the model 'thought' at each step, debugging, or research.",
                "To calculate memory usage for logits, each logit is typically a 32-bit float which is 4 bytes. The formula is sequence length times vocabulary size times 4 bytes.",
                "A 2048 token context with a 32k vocabulary works out to 2048 × 32000 × 4 = 262 MB. A 4096 token context with a 128k vocabulary like Llama 3 uses 4096 × 128000 × 4 = 2.1 GB.",
                "With logits_all off you only get logits for the last token, so just vocabulary size times 4 bytes, around 128-512 KB depending on vocabulary size. That's why it's off by default.",
                "When to enable it: Computing perplexity scores, analyzing model behavior at each token, certain research/debugging scenarios.",
                "When to leave it off: Normal chat/completion use cases, when you just want generated text, when memory is constrained.",
                "For typical inference and chat applications, keep it off to save memory and improve performance.",
                "Perplexity is a metric that measures how well a language model predicts a sequence of text. Lower perplexity means the model is less 'surprised' by the text and assigns higher probabilities to the actual tokens that appear.",
                "Mathematically it's the exponentiated average negative log-likelihood per token. If a model assigns high probability to each token in a sequence, the perplexity is low. If the model is often wrong about what comes next, perplexity is high.",
                "To calculate perplexity you need the probability distribution over the entire vocabulary at each position in the sequence, not just the final prediction. That's why logits_all must be enabled — it returns the raw scores for every token at every position, which you then convert to probabilities and use to compute how likely the actual text was under the model.",
                "Common uses include comparing model quality, evaluating fine-tuning results, and measuring how well a model fits a particular domain of text. A model fine-tuned on legal documents should have lower perplexity on legal text than a general-purpose model.",
                "If perplexity is high it means the model is struggling to predict the text well. A few approaches depending on the cause:",
                "If the text is out of domain, fine-tune the model on similar data. A general model will have high perplexity on specialized text like legal documents or code because it wasn't trained heavily on that style.",
                "If the model is too small, try a larger model. Bigger models generally have lower perplexity because they capture more patterns and nuances.",
                "If the tokenizer is mismatched, make sure you're using the correct tokenizer for the model. Wrong tokenization produces garbage inputs and high perplexity.",
                "If the text itself is unusual or noisy, that's expected. Random text, heavy jargon, typos, or multiple languages mixed together will naturally produce high perplexity.",
                "If you're evaluating your own fine-tuned model and perplexity increased after training, you may have overfit to training data, used a learning rate that was too high, or trained for too many epochs. Check perplexity on both training and validation sets to diagnose.",
                "Sometimes high perplexity is just information — it tells you the model doesn't fit that data well, which may be fine depending on your use case.",
            ],
            Self::VocabOnly => vec![
                "Load only the vocabulary without model weights.",
                "Useful for tokenization tasks without running inference.",
            ],
            Self::Reload => vec![
                "The Reload button refreshes the list of available models from the backend.",
                "After starting a new model server: If you just launched Ollama, vLLM, or another backend, the model list may not have been available when the page first loaded.",
                "After pulling/downloading new models: If you ran `ollama pull llama3` or downloaded a new model, click Reload to see it in the dropdown.",
                "After deleting models: To update the list after removing models from the backend.",
                "If the initial fetch failed: Network issues or backend not ready can cause the first load to fail; Reload lets you retry.",
                "To check for newly available models: Some backends may have models added dynamically.",
            ],
            Self::RopeTuning => vec![
                "RoPE (Rotary Position Embedding) tuning refers to adjusting the positional encoding parameters to extend a model's context length beyond what it was originally trained on.",
                "RoPE encodes position information by rotating the query and key vectors in the attention mechanism. The rotation angle depends on the position and a base frequency parameter, typically 10000 by default.",
                "To extend context length you can adjust the base frequency. Increasing it (like to 500000 in Llama 3) compresses the position signal, letting the model handle longer sequences. This is sometimes called 'base frequency scaling' or adjusting rope_freq_base.",
                "Another approach is linear scaling where you multiply position indices by a factor. If a model was trained on 4k context and you want 16k, you scale positions by 0.25 so the model sees familiar position values. The rope_freq_scale parameter controls this.",
                "YaRN (Yet another RoPE extensioN) combines frequency scaling with attention temperature adjustments for better quality at extended lengths.",
                "The tradeoff is that extending context too aggressively degrades quality. The model wasn't trained to attend over those distances so it may lose coherence or miss relevant context. Fine-tuning on longer sequences after adjusting RoPE parameters helps but isn't always necessary for moderate extensions.",
                "In llama.cpp you can set rope_freq_base and rope_freq_scale directly when loading a model.",
            ],
            Self::Temperature => vec![
                "Temperature controls the randomness of the model's output. Range: 0.0 to 2.0.",
                "Lower values (0.1-0.5) make output more focused and deterministic — the model picks high-probability tokens.",
                "Higher values (0.7-1.2) increase creativity and diversity — the model is more willing to pick less likely tokens.",
                "At 0, the model always picks the most probable token (greedy decoding). At 2.0, output becomes very random.",
                "For factual tasks use 0.1-0.3. For creative writing use 0.7-1.0. Default is typically 0.7.",
            ],
            Self::TopK => vec![
                "Top-K limits token selection to the K most probable tokens at each step.",
                "After the model computes probabilities, only the top K tokens are considered; all others are set to zero probability.",
                "Lower K (10-40) makes output more focused. Higher K (100+) allows more variety.",
                "K=1 is equivalent to greedy decoding. K=40 is a common default.",
                "Top-K is a hard cutoff — if a token isn't in the top K, it cannot be chosen regardless of its probability.",
            ],
            Self::TopP => vec![
                "Top-P (nucleus sampling) selects from the smallest set of tokens whose cumulative probability exceeds P.",
                "Unlike Top-K which uses a fixed count, Top-P adapts to the probability distribution.",
                "When the model is confident (one token dominates), fewer tokens are considered. When uncertain, more tokens qualify.",
                "P=0.9 means tokens are included until their cumulative probability reaches 90%.",
                "Top-P is often preferred over Top-K because it adapts to context. Common values: 0.9-0.95.",
            ],
            Self::MinP => vec![
                "Min-P filters out tokens with probability below a minimum threshold relative to the top token.",
                "If the top token has probability 0.5 and min_p=0.1, tokens below 0.05 (0.5 × 0.1) are excluded.",
                "This prevents very unlikely tokens from being selected while adapting to the model's confidence.",
                "Min-P is useful for reducing nonsensical outputs without being as restrictive as low Top-K.",
                "Common values: 0.05-0.1. Set to 0 to disable.",
            ],
            Self::TypicalP => vec![
                "Typical-P (locally typical sampling) selects tokens based on their information content (entropy).",
                "Instead of just probability, it considers how 'typical' or 'surprising' each token is in context.",
                "Tokens that are neither too predictable nor too surprising are preferred.",
                "This can produce more natural-sounding text by avoiding both obvious and bizarre choices.",
                "Common values: 0.9-1.0. Set to 1.0 to disable.",
            ],
            Self::TfsZ => vec![
                "Tail Free Sampling (TFS) removes the 'tail' of the probability distribution.",
                "It analyzes the rate of change in token probabilities and cuts off where the distribution flattens.",
                "This removes low-probability tokens that add noise without contributing meaningfully.",
                "Z parameter controls aggressiveness: lower values cut more aggressively.",
                "Common values: 0.9-1.0. Set to 1.0 to disable.",
            ],
            Self::Seed => vec![
                "Seed initializes the random number generator for reproducible outputs.",
                "With the same seed, prompt, and settings, the model produces identical output.",
                "Useful for debugging, testing, or when you want to reproduce a specific generation.",
                "Leave empty or set to 0 for random seed (different output each time).",
                "Any positive integer works as a seed. The specific number doesn't affect quality.",
            ],
            Self::RepeatLastN => vec![
                "Controls how many recent tokens are considered when applying repetition penalties.",
                "The model looks back this many tokens to check for repetition. Default is 64.",
                "Higher values catch longer-range repetition but may over-penalize common words.",
                "Lower values only penalize immediate repetition.",
                "Set to 0 to disable repetition penalty entirely, or -1 to consider all tokens.",
            ],
            Self::RepeatPenalty => vec![
                "Multiplier applied to tokens that have already appeared in the context.",
                "Values > 1.0 discourage repetition. Default is 1.1.",
                "1.0 means no penalty. Higher values (1.2-1.5) strongly discourage repeating words.",
                "Too high values can make output unnatural by avoiding necessary repetition.",
                "Works with repeat_last_n to define the lookback window.",
            ],
            Self::PresencePenalty => vec![
                "Flat penalty applied to any token that has appeared at least once.",
                "Unlike repeat_penalty, this doesn't scale with how many times a token appeared.",
                "Encourages the model to talk about new topics rather than staying on one subject.",
                "Range: 0.0 to 2.0. Default is 0.0 (disabled).",
                "Useful for creative writing where you want diverse vocabulary.",
            ],
            Self::FrequencyPenalty => vec![
                "Penalty that scales with how often a token has appeared.",
                "The more times a token appears, the stronger the penalty becomes.",
                "More aggressive than presence_penalty for heavily repeated words.",
                "Range: 0.0 to 2.0. Default is 0.0 (disabled).",
                "Useful for reducing word repetition in longer outputs.",
            ],
            Self::PenalizeNewline => vec![
                "Whether to apply repetition penalties to newline characters.",
                "When enabled, the model is discouraged from producing many newlines.",
                "When disabled, newlines are exempt from repetition penalties.",
                "Disable for code generation or formatted output where newlines are structural.",
                "Enable for prose where excessive line breaks are undesirable.",
            ],
            Self::Mirostat => vec![
                "Mirostat is an adaptive sampling algorithm that maintains consistent output quality.",
                "Mode 0: Disabled - uses standard sampling (temperature, top-k, top-p).",
                "Mode 1: Mirostat v1 - original algorithm, good for most use cases.",
                "Mode 2: Mirostat v2 - improved version, often produces better results.",
                "When enabled, Mirostat overrides top-k and top-p settings.",
                "Useful for maintaining coherent output over long generations.",
            ],
            Self::MirostatTau => vec![
                "Target entropy (perplexity) that Mirostat tries to maintain.",
                "Controls the 'surprise' level of the output. Default is 5.0.",
                "Lower values (2-4) produce more focused, predictable text.",
                "Higher values (6-8) allow more creative, varied output.",
                "The algorithm adjusts sampling dynamically to hit this target.",
            ],
            Self::MirostatEta => vec![
                "Learning rate for Mirostat's adaptive algorithm. Default is 0.1.",
                "Controls how quickly Mirostat adjusts to reach target entropy.",
                "Lower values (0.05) make slower, more stable adjustments.",
                "Higher values (0.2) react faster but may overshoot.",
                "Most users should leave this at the default value.",
            ],
            Self::NumPredict => vec![
                "Maximum number of tokens to generate in the response.",
                "Set to -1 for unlimited generation (model decides when to stop).",
                "Set to -2 to fill the context window completely.",
                "Positive values limit output length. Default varies by model.",
                "Useful for controlling response length and API costs.",
            ],
            Self::NumKeep => vec![
                "Number of tokens to keep from the initial prompt when context fills up.",
                "When the context window is full, older tokens are removed but num_keep tokens from the start are preserved.",
                "Set to 0 to not keep any initial tokens (default).",
                "Set to -1 to keep all initial prompt tokens.",
                "Useful for maintaining system prompts or important context.",
            ],
            Self::StopSequences => vec![
                "Strings that tell the model to stop generating. When the model outputs any of these sequences, generation halts immediately — the stop string itself is not included in the output.",
                "Enter multiple sequences separated by commas. Example: </s>, ###, <|end|>",
                "Works for both llama-server and Ollama backends — sent as a per-request parameter on every inference call.",
                "Common use cases: preventing the model from continuing past a known end-of-answer marker, enforcing structured output boundaries, or stopping at role separators in chat templates.",
                "Leave blank to let the model run until max_tokens or its built-in EOS token.",
            ],
            Self::Quantization => vec![
                "Quantization reduces model precision to save memory. Lower bits = smaller size but slightly reduced quality.",
                "Common levels: q4_0 (4-bit, smallest), q5_k_m (5-bit, balanced), q8_0 (8-bit, high quality), f16 (16-bit, full precision).",
                "With Ollama, quantization is set when you PULL the model, not at runtime. The model tag determines the quantization.",
                "Example: 'phi3.5:latest' and 'phi3.5:3.8b-mini-instruct-q4_0' are the SAME model if they share the same ID.",
                "To use a different quantization, pull a model with that specific tag: 'ollama pull phi3:3.8b-mini-instruct-q8_0'.",
                "The recommendation shown here helps you choose which quantization tag to pull based on your available RAM.",
                "If size detection fails (shows 'Could not detect'), include the size in the model name like 'llama3:7b' or 'phi3:3.8b'.",
            ],

            Self::SplitMode => vec![
                "split_mode controls how llama.cpp splits work across multiple GPUs (when multi-GPU offload is used).",
                "",
                "Modes",
                "• none: no splitting (single GPU / default)",
                "• layer: split by transformer layers (common for multi-GPU)",
                "• row: split tensors more finely (can help balance VRAM, but may be slower)",
                "",
                "Notes",
                "• If you only have one GPU, split_mode usually has no effect.",
            ],
            Self::NumUBatch => vec![
                "num_ubatch controls micro-batching (a smaller sub-batch size used inside a larger batch).",
                "",
                "Why it matters",
                "Micro-batching can improve throughput without exceeding memory limits, but it depends on model + hardware.",
                "",
                "Notes",
                "• If you hit OOM, reduce num_ubatch (or num_batch).",
            ],
            Self::NumSeqMax => vec![
                "num_seq_max limits how many sequences can be tracked in a single context.",
                "",
                "When it matters",
                "This is mostly relevant for server-like usage, parallel requests, or advanced batching.",
                "",
                "Notes",
                "• Higher values can increase memory usage.",
            ],
            Self::FlashAttn => vec![
                "flash_attn enables a faster / more memory-efficient attention implementation (when supported by the build and device).",
                "",
                "Notes",
                "• If you see instability or unexpected behavior, try disabling it.",
            ],
            Self::OffloadKqv => vec![
                "offload_kqv controls whether attention K/Q/V tensors and related work are offloaded to GPU.",
                "",
                "Trade-off",
                "• On can improve speed, but increases VRAM usage.",
                "• Off can reduce VRAM pressure, but may be slower.",
            ],
            Self::Embeddings => vec![
                "embeddings toggles whether the backend produces embedding vectors (in addition to text generation), when supported.",
                "",
                "Notes",
                "• Embeddings are used for semantic search / retrieval.",
                "• If you turn this off, retrieval features may stop working or fall back depending on configuration.",
            ],
            Self::NumThreadBatch => vec![
                "num_thread_batch controls how many CPU threads are used for batch-related work.",
                "",
                "Notes",
                "• Start near num_thread (or slightly lower).",
                "• Too high can cause contention.",
            ],
            Self::CpuStrict => vec![
                "cpu_strict controls how strictly the runtime binds/limits CPU scheduling decisions.",
                "",
                "Notes",
                "• Can improve predictability on dedicated machines.",
                "• Can reduce responsiveness on shared desktops.",
            ],
            Self::Poll => vec![
                "poll controls a polling interval (in microseconds) used by some waiting/scheduling loops.",
                "",
                "Trade-off",
                "• Lower values can reduce latency but increase CPU usage.",
                "• Higher values can reduce CPU usage but increase latency.",
            ],
            Self::Priority => vec![
                "priority controls the scheduling priority for inference work.",
                "",
                "Trade-off",
                "Higher priority can improve latency/throughput, but can starve other processes.",
            ],
            Self::IgnoreEos => vec![
                "ignore_eos makes generation ignore the model's end-of-sequence token.",
                "",
                "Notes",
                "• Useful if a model stops too early.",
                "• Add stop sequences to avoid runaway generation.",
            ],
            Self::SamplingParams => vec![
                "When a language model generates text, it does not simply pick the single most likely next token. Instead it samples — drawing from a probability distribution over its vocabulary.",
                "Sampling parameters shape that distribution before the draw happens. They let you trade off between predictability and creativity, and suppress unwanted patterns like repetition.",
                "",
                "Use cases",
                "Factual / RAG answers: low temperature (0.1–0.4), top-p 0.9, no mirostat. The model stays close to what the retrieval context says.",
                "Creative writing: higher temperature (0.7–1.2), top-p 0.95, repeat penalty on. Gives the model more freedom to surprise.",
                "Code generation: low temperature (0.1–0.3), deterministic seed. Reproducibility matters more than variety.",
                "Chat / assistant: moderate temperature (0.5–0.8). Balances coherence with natural-feeling variation.",
                "",
                "These settings apply per inference — they do not affect retrieval, chunking, or embedding.",
            ],
            Self::DryMultiplier => vec![
                "DRY (Don't Repeat Yourself) is a repetition penalty that targets exact repeated sequences rather than just repeated individual tokens.",
                "dry_multiplier is the main strength knob. At 0.0 DRY is disabled entirely. Values around 0.8–1.2 provide a noticeable but not aggressive penalty.",
                "Unlike repeat_penalty which penalises any token that appeared before, DRY only fires when the model is about to reproduce a sequence it has already output verbatim.",
                "This makes it much more effective against loops and copy-paste repetition without hurting normal word reuse.",
                "Start with 0.8 and increase toward 1.5 if you still see loops. Setting it above 2.0 can make output feel stilted.",
            ],
            Self::DryBase => vec![
                "dry_base controls how exponentially the DRY penalty grows as the repeated sequence gets longer.",
                "A value of 1.75 means: penalty = dry_multiplier × dry_base^(matched_length - dry_allowed_length).",
                "Longer repeated sequences get penalised much harder than short ones — a 6-token repeat hurts far more than a 2-token repeat.",
                "Higher dry_base values (2.0+) create a very steep curve: the model can repeat short common phrases freely but is severely penalised for reproducing longer passages.",
                "Lower values (1.2–1.5) apply a more gradual curve. The default of 1.75 is a good balance for most use cases.",
            ],
            Self::DryAllowedLen => vec![
                "dry_allowed_length sets a minimum sequence length before the DRY penalty kicks in.",
                "If dry_allowed_length is 2, the model can freely repeat any single token or bigram without penalty. The penalty only fires when 3 or more tokens in a row match a previous sequence.",
                "This prevents punishing legitimate reuse of short common phrases (e.g., 'the', 'of the', 'in order to').",
                "Raise this value if DRY is interfering with structured output like markdown tables or code that naturally repeats short patterns.",
                "Lower it (set to 1) if you want to catch even single-token repetition loops.",
            ],
            Self::XtcProbability => vec![
                "XTC (eXclude Top Choices) is a sampling method that deliberately removes the most probable tokens from consideration, forcing the model toward less obvious but often more interesting choices.",
                "xtc_probability controls how often XTC is applied. At 0.0 it is disabled. At 1.0 it fires on every token selection.",
                "Intermediate values like 0.1–0.3 apply XTC probabilistically, so only some token selections are affected. This creates a mix of normal and XTC-filtered choices.",
                "XTC is most useful for creative writing where you want to avoid predictable, bland continuations.",
                "Combine with a moderate temperature (0.7–1.0). Using XTC with very low temperature often produces poor results because all remaining tokens after exclusion have low probability.",
                "Set to 0.0 (disabled) for factual tasks, Q&A, coding, or any task where the most probable token is usually correct.",
            ],
            Self::XtcThreshold => vec![
                "xtc_threshold defines the minimum probability a token must have to be eligible for exclusion by XTC.",
                "Only tokens with probability >= xtc_threshold are removed from consideration. Tokens below this threshold are always kept.",
                "At 0.1 (the typical default), any token with >= 10% probability is excluded when XTC fires. Lower values make XTC more aggressive by excluding even less-probable tokens.",
                "Higher values (0.3+) make XTC conservative — only dominant tokens are excluded, leaving more of the distribution intact.",
                "This works together with xtc_probability: xtc_probability decides how often XTC fires; xtc_threshold decides which tokens it removes when it does fire.",
                "If your output becomes incoherent after enabling XTC, try raising xtc_threshold toward 0.2–0.3 to limit which tokens get excluded.",
            ],
        }
    }
}
