//! Help content for ONNX Runtime configuration parameters.

/// Enumeration of all help topics available in the ONNX configuration page.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OnnxHelpTopic {
    // Session Options
    GraphOptimizationLevel,
    ExecutionMode,
    NumThreads,
    InterOpNumThreads,
    EnableMemPattern,
    EnableCpuMemArena,
    DeterministicCompute,
    OptimizedModelFilepath,
    EnableProfiling,
    ProfilingOutputPath,
    LogId,
    LogLevel,
    LogVerbosity,
    UseEnvAllocators,
    DenormalAsZero,
    UseDeviceAllocatorForInitializers,
    AllowInterOpSpinning,
    AllowIntraOpSpinning,
    UsePrepacking,
    IndependentThreadPool,
    NoEnvExecutionProviders,
    // Graph Optimizations
    EnableQuantQdq,
    EnableDoubleQdqRemover,
    EnableQdqCleanup,
    ApproximateGelu,
    EnableAotInlining,
    DisabledOptimizers,
    // Model Settings
    ModelPath,
    EmbeddingDim,
    MaxLength,
}

impl OnnxHelpTopic {
    /// Returns the title for this help topic.
    pub fn title(&self) -> &'static str {
        match self {
            Self::GraphOptimizationLevel => "graph_optimization_level",
            Self::ExecutionMode => "execution_mode",
            Self::NumThreads => "num_threads (intra-op)",
            Self::InterOpNumThreads => "inter_op_num_threads",
            Self::EnableMemPattern => "enable_mem_pattern",
            Self::EnableCpuMemArena => "enable_cpu_mem_arena",
            Self::DeterministicCompute => "use_deterministic_compute",
            Self::OptimizedModelFilepath => "optimized_model_filepath",
            Self::EnableProfiling => "enable_profiling",
            Self::ProfilingOutputPath => "profiling_output_path",
            Self::LogId => "log_id",
            Self::LogLevel => "log_level",
            Self::LogVerbosity => "log_verbosity",
            Self::UseEnvAllocators => "use_env_allocators",
            Self::DenormalAsZero => "denormal_as_zero",
            Self::UseDeviceAllocatorForInitializers => "use_device_allocator_for_initializers",
            Self::AllowInterOpSpinning => "allow_inter_op_spinning",
            Self::AllowIntraOpSpinning => "allow_intra_op_spinning",
            Self::UsePrepacking => "use_prepacking",
            Self::IndependentThreadPool => "independent_thread_pool",
            Self::NoEnvExecutionProviders => "no_env_execution_providers",
            Self::EnableQuantQdq => "enable_quant_qdq",
            Self::EnableDoubleQdqRemover => "enable_double_qdq_remover",
            Self::EnableQdqCleanup => "enable_qdq_cleanup",
            Self::ApproximateGelu => "approximate_gelu",
            Self::EnableAotInlining => "enable_aot_inlining",
            Self::DisabledOptimizers => "disabled_optimizers",
            Self::ModelPath => "model_path",
            Self::EmbeddingDim => "embedding_dim",
            Self::MaxLength => "max_length",
        }
    }

    /// Returns the help paragraphs for this topic.
    pub fn paragraphs(&self) -> Vec<&'static str> {
        match self {
            Self::GraphOptimizationLevel => vec![
                "Controls how aggressively ONNX Runtime optimizes the computation graph before execution.",
                "Level 0 (Off): No optimizations. Use for debugging or when optimizations cause issues.",
                "Level 1 (Basic): Safe optimizations like constant folding and redundant node elimination.",
                "Level 2 (Extended): More aggressive optimizations including operator fusion.",
                "Level 3 (All): Maximum optimization including layout transformations. Best for production.",
                "Higher levels increase session initialization time but improve inference speed.",
            ],
            Self::ExecutionMode => vec![
                "Determines how operators are scheduled during inference.",
                "Sequential: Operators execute one at a time in topological order. Lower memory usage, predictable behavior.",
                "Parallel: Independent operators can run concurrently using inter_op_num_threads. Higher throughput for graphs with parallelism.",
                "Sequential is recommended for most embedding models. Parallel benefits complex models with independent branches.",
            ],
            Self::NumThreads => vec![
                "Number of threads for intra-operator parallelism (within a single operator).",
                "Controls parallelism for operations like matrix multiplication within a single layer.",
                "Set to number of physical CPU cores for best performance.",
                "Setting too high can cause thread contention and hurt performance.",
                "Default: 4 threads.",
            ],
            Self::InterOpNumThreads => vec![
                "inter_op_num_threads controls how many operators can execute simultaneously when the computation graph has independent branches.",
                "Think of a graph like: Input → (Op A, Op B) → Op C. Op A and Op B don't depend on each other.",
                "With inter_op_num_threads=2, Op A and Op B can run at the same time on separate threads. With inter_op_num_threads=1, they run sequentially even though they're independent.",
                "For transformer models this rarely matters much because the graph is mostly linear—each attention layer depends on the previous one.",
                "But for models with parallel branches (some vision models, encoder-decoder architectures, models with multiple heads that get computed independently before merging), it can help.",
                "The threads here are essentially a thread pool for scheduling operators, not for doing the math within each op (that's what intra_op threads do).",
                "In practice, most people leave it at 1 or 2 and focus on tuning intra_op_num_threads instead, since that's where the heavy compute actually happens.",
                "Default: 1 thread.",
            ],
            Self::EnableMemPattern => vec![
                "Enables memory pattern optimization to reduce memory allocation overhead.",
                "When enabled, ONNX Runtime pre-allocates memory based on the execution pattern.",
                "Reduces runtime memory allocation calls, improving performance.",
                "May increase initial memory usage slightly.",
                "Default: true (enabled).",
            ],
            Self::EnableCpuMemArena => vec![
                "Enables the CPU memory arena for more efficient memory management.",
                "Pre-allocates a memory pool to reduce allocation/deallocation overhead.",
                "Particularly beneficial for repeated inference calls.",
                "May increase baseline memory usage.",
                "Default: true (enabled).",
            ],
            Self::DeterministicCompute => vec![
                "Forces deterministic computation when possible.",
                "When enabled, the same inputs will always produce identical outputs.",
                "May disable some optimizations that introduce non-determinism.",
                "Useful for debugging and reproducibility testing.",
                "Default: false (disabled for better performance).",
            ],
            Self::OptimizedModelFilepath => vec![
                "Path to save the optimized model after graph optimizations.",
                "If set, ONNX Runtime writes the optimized graph to this file.",
                "Useful for inspecting what optimizations were applied.",
                "Can be loaded directly in future sessions to skip optimization.",
                "Leave empty to disable.",
            ],
            Self::EnableProfiling => vec![
                "Enables profiling to collect performance metrics.",
                "When enabled, generates a Chrome trace JSON file for analysis.",
                "Use Chrome's chrome://tracing to visualize the profile.",
                "Adds overhead during inference - disable for production.",
                "Default: false (disabled).",
            ],
            Self::ProfilingOutputPath => vec![
                "Path where profiling output will be written.",
                "Only used when enable_profiling is true.",
                "Output is in Chrome trace format (.json).",
                "Leave empty to use default location.",
            ],
            Self::LogId => vec![
                "Custom identifier for ONNX Runtime log messages.",
                "Helps distinguish logs from different sessions.",
                "Useful when running multiple ONNX sessions.",
                "Leave empty for default logging.",
            ],
            Self::LogLevel => vec![
                "Minimum severity level for ONNX Runtime log messages.",
                "Verbose: All messages including debug info.",
                "Info: Informational messages and above.",
                "Warning: Warnings and errors only.",
                "Error: Only error messages.",
                "Fatal: Only fatal errors.",
                "Default: Info.",
            ],
            Self::LogVerbosity => vec![
                "Verbosity level for verbose logging (0 or higher).",
                "Only applies when log_level is set to Verbose.",
                "Higher values produce more detailed output.",
                "Default: 0.",
            ],
            Self::UseEnvAllocators => vec![
                "Use environment-level allocators instead of session-specific ones.",
                "When enabled, memory allocators are shared across sessions.",
                "Can reduce memory fragmentation with multiple sessions.",
                "Default: false (each session has its own allocators).",
            ],
            Self::DenormalAsZero => vec![
                "Enables flush-to-zero and denormal-as-zero CPU modes.",
                "Treats very small floating-point numbers as zero.",
                "Can significantly speed up computation on some CPUs.",
                "May slightly reduce numerical precision for edge cases.",
                "Default: false (disabled).",
            ],
            Self::UseDeviceAllocatorForInitializers => vec![
                "Use device allocator when initializing model tensors.",
                "Can improve memory locality for GPU execution.",
                "For CPU-only inference, usually not needed.",
                "Default: false (disabled).",
            ],
            Self::AllowInterOpSpinning => vec![
                "Allow inter-op threads to spin briefly before blocking.",
                "Spinning can reduce latency for quick operations.",
                "Uses more CPU when threads are idle.",
                "Default: true (enabled).",
            ],
            Self::AllowIntraOpSpinning => vec![
                "Allow intra-op threads to spin briefly before blocking.",
                "Similar to inter-op spinning but for within-operator parallelism.",
                "Can reduce latency at the cost of CPU usage.",
                "Default: true (enabled).",
            ],
            Self::UsePrepacking => vec![
                "Enable prepacking optimizations for weights.",
                "Rearranges weight tensors for more efficient computation.",
                "Increases initialization time but improves inference speed.",
                "Default: true (enabled).",
            ],
            Self::IndependentThreadPool => vec![
                "Use an independent thread pool for this session.",
                "When enabled, session doesn't share threads with other sessions.",
                "Useful for isolating workloads or ensuring thread availability.",
                "Default: false (shares thread pool).",
            ],
            Self::NoEnvExecutionProviders => vec![
                "Don't inherit execution providers from the environment.",
                "When enabled, only explicitly added providers are used.",
                "Useful for controlling exactly which providers are active.",
                "Default: false (inherits environment providers).",
            ],
            Self::EnableQuantQdq => vec![
                "Enable Quantize/Dequantize (QDQ) fusion optimizations.",
                "Fuses quantization operations for better performance.",
                "Essential for running quantized models efficiently.",
                "Default: true (enabled).",
            ],
            Self::EnableDoubleQdqRemover => vec![
                "Enable the pass that removes redundant double QDQ nodes.",
                "Cleans up unnecessary quantize-dequantize pairs.",
                "Improves performance of quantized models.",
                "Default: true (enabled).",
            ],
            Self::EnableQdqCleanup => vec![
                "Remove QDQ nodes after processing completes.",
                "Final cleanup pass for quantization nodes.",
                "Usually not needed if other QDQ optimizations are enabled.",
                "Default: false (disabled).",
            ],
            Self::ApproximateGelu => vec![
                "Use approximate GELU activation instead of exact computation.",
                "GELU (Gaussian Error Linear Unit) is common in transformers.",
                "Approximation is faster with minimal accuracy loss.",
                "Default: false (uses exact GELU).",
            ],
            Self::EnableAotInlining => vec![
                "Enable ahead-of-time function inlining.",
                "Inlines function calls during graph optimization.",
                "Can improve performance by reducing call overhead.",
                "Default: true (enabled).",
            ],
            Self::DisabledOptimizers => vec![
                "List of optimizer names to disable.",
                "Comma-separated list of optimizer identifiers.",
                "Use when specific optimizations cause issues.",
                "Leave empty to enable all optimizers.",
            ],
            Self::ModelPath => vec![
                "Path to the ONNX model file.",
                "Supports .onnx format models.",
                "Can be absolute or relative to the working directory.",
                "Default: models/embedding_model.onnx",
            ],
            Self::EmbeddingDim => vec![
                "Dimension of the output embedding vectors.",
                "Must match the model's actual output dimension.",
                "Common values: 384 (MiniLM), 768 (BERT-base), 1024 (BERT-large).",
                "Default: 384.",
            ],
            Self::MaxLength => vec![
                "Maximum sequence length for input tokenization.",
                "Inputs longer than this are truncated.",
                "Must not exceed the model's maximum position embeddings.",
                "Default: 512 tokens.",
            ],
        }
    }
}
