//! Help content for ONNX Runtime configuration parameters.

/// Enumeration of all help topics available in the ONNX configuration page.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OnnxHelpTopic {
    // Session Options
    GraphOptimizationLevel,
    ExecutionMode,
    NumThreads,
    InterOpNumThreads,
    EnableMemPattern,
    EnableCpuMemArena,
    DeterministicCompute,
    OptimizedModelFilepath,
    EnableProfiling,
    ProfilingOutputPath,
    LogId,
    LogLevel,
    LogVerbosity,
    UseEnvAllocators,
    DenormalAsZero,
    UseDeviceAllocatorForInitializers,
    AllowInterOpSpinning,
    AllowIntraOpSpinning,
    UsePrepacking,
    IndependentThreadPool,
    NoEnvExecutionProviders,
    // Graph Optimizations
    EnableQuantQdq,
    EnableDoubleQdqRemover,
    EnableQdqCleanup,
    ApproximateGelu,
    EnableAotInlining,
    DisabledOptimizers,
    // Model Settings
    ModelPath,
    EmbeddingDim,
    MaxLength,
    // Session Options (read-only / advanced)
    ExecutionOrder,
    CustomCreateThreadFn,
    CustomJoinThreadFn,
    FreeDimensionOverrides,
    SessionConfigEntries,
    // Session Config Keys
    SaveModelFormat,
    UseOrtModelBytesDirectly,
    UseOrtModelBytesForInitializers,
    IntraOpSpinControl,
    DynamicBlockBase,
    GraphOptimizationsLoopLevel,
    EnableBiasGeluFusion,
    EnableConvBnFusion,
    // Run Options
    RunTag,
    RunLogSeverityLevel,
    RunLogVerbosityLevel,
    LogTag,
    // CPU Execution Provider
    EpIntraOpNumThreads,
    EpInterOpNumThreads,
    UseArena,
    ArenaExtendStrategy,
    InitialChunkSizeBytes,
    MaxChunkSizeBytes,
    InitialGrowthChunkSizeBytes,
    MaxDeadBytesPerChunk,
}

impl OnnxHelpTopic {
    /// Returns the title for this help topic.
    pub fn title(&self) -> &'static str {
        match self {
            Self::GraphOptimizationLevel => "graph_optimization_level",
            Self::ExecutionMode => "execution_mode",
            Self::NumThreads => "num_threads (intra-op)",
            Self::InterOpNumThreads => "inter_op_num_threads",
            Self::EnableMemPattern => "enable_mem_pattern",
            Self::EnableCpuMemArena => "enable_cpu_mem_arena",
            Self::DeterministicCompute => "use_deterministic_compute",
            Self::OptimizedModelFilepath => "optimized_model_filepath",
            Self::EnableProfiling => "enable_profiling",
            Self::ProfilingOutputPath => "profiling_output_path",
            Self::LogId => "log_id",
            Self::LogLevel => "log_level",
            Self::LogVerbosity => "log_verbosity",
            Self::UseEnvAllocators => "use_env_allocators",
            Self::DenormalAsZero => "denormal_as_zero",
            Self::UseDeviceAllocatorForInitializers => "use_device_allocator_for_initializers",
            Self::AllowInterOpSpinning => "allow_inter_op_spinning",
            Self::AllowIntraOpSpinning => "allow_intra_op_spinning",
            Self::UsePrepacking => "use_prepacking",
            Self::IndependentThreadPool => "independent_thread_pool",
            Self::NoEnvExecutionProviders => "no_env_execution_providers",
            Self::EnableQuantQdq => "enable_quant_qdq",
            Self::EnableDoubleQdqRemover => "enable_double_qdq_remover",
            Self::EnableQdqCleanup => "enable_qdq_cleanup",
            Self::ApproximateGelu => "approximate_gelu",
            Self::EnableAotInlining => "enable_aot_inlining",
            Self::DisabledOptimizers => "disabled_optimizers",
            Self::ModelPath => "model_path",
            Self::EmbeddingDim => "embedding_dim",
            Self::MaxLength => "max_length",
            Self::ExecutionOrder => "execution_order",
            Self::CustomCreateThreadFn => "custom_create_thread_fn",
            Self::CustomJoinThreadFn => "custom_join_thread_fn",
            Self::FreeDimensionOverrides => "free_dimension_overrides",
            Self::SessionConfigEntries => "session_config_entries",
            Self::SaveModelFormat => "session.save_model_format",
            Self::UseOrtModelBytesDirectly => "session.use_ort_model_bytes_directly",
            Self::UseOrtModelBytesForInitializers => "session.use_ort_model_bytes_for_initializers",
            Self::IntraOpSpinControl => "session.intra_op.spin_control",
            Self::DynamicBlockBase => "session.dynamic_block_base",
            Self::GraphOptimizationsLoopLevel => "session.graph_optimizations_loop_level",
            Self::EnableBiasGeluFusion => "optimization.enable_bias_gelu_fusion",
            Self::EnableConvBnFusion => "optimization.enable_conv_bn_fusion",
            Self::RunTag => "run_tag",
            Self::RunLogSeverityLevel => "log_severity_level (run)",
            Self::RunLogVerbosityLevel => "log_verbosity_level (run)",
            Self::LogTag => "log_tag",
            Self::EpIntraOpNumThreads => "intra_op_num_threads (CPU EP)",
            Self::EpInterOpNumThreads => "inter_op_num_threads (CPU EP)",
            Self::UseArena => "use_arena",
            Self::ArenaExtendStrategy => "arena_extend_strategy",
            Self::InitialChunkSizeBytes => "initial_chunk_size_bytes",
            Self::MaxChunkSizeBytes => "max_chunk_size_bytes",
            Self::InitialGrowthChunkSizeBytes => "initial_growth_chunk_size_bytes",
            Self::MaxDeadBytesPerChunk => "max_dead_bytes_per_chunk",
        }
    }

    /// Returns the help paragraphs for this topic.
    pub fn paragraphs(&self) -> Vec<&'static str> {
        match self {
            Self::GraphOptimizationLevel => vec![
                "Controls how aggressively ONNX Runtime optimizes the computation graph before execution.",
                "Level 0 (Off): No optimizations. Use for debugging or when optimizations cause issues.",
                "Level 1 (Basic): Safe optimizations like constant folding and redundant node elimination.",
                "Level 2 (Extended): More aggressive optimizations including operator fusion.",
                "Level 3 (All): Maximum optimization including layout transformations. Best for production.",
                "Higher levels increase session initialization time but improve inference speed.",
            ],
            Self::ExecutionMode => vec![
                "Determines how operators are scheduled during inference.",
                "Sequential: Operators execute one at a time in topological order. Lower memory usage, predictable behavior.",
                "Parallel: Independent operators can run concurrently using inter_op_num_threads. Higher throughput for graphs with parallelism.",
                "Sequential is recommended for most embedding models. Parallel benefits complex models with independent branches.",
            ],
            Self::NumThreads => vec![
                "Number of threads for intra-operator parallelism (within a single operator).",
                "Controls parallelism for operations like matrix multiplication within a single layer.",
                "Set to number of physical CPU cores for best performance.",
                "Setting too high can cause thread contention and hurt performance.",
                "Default: 4 threads.",
            ],
            Self::InterOpNumThreads => vec![
                "inter_op_num_threads controls how many operators can execute simultaneously when the computation graph has independent branches.",
                "Think of a graph like: Input → (Op A, Op B) → Op C. Op A and Op B don't depend on each other.",
                "With inter_op_num_threads=2, Op A and Op B can run at the same time on separate threads. With inter_op_num_threads=1, they run sequentially even though they're independent.",
                "For transformer models this rarely matters much because the graph is mostly linear—each attention layer depends on the previous one.",
                "But for models with parallel branches (some vision models, encoder-decoder architectures, models with multiple heads that get computed independently before merging), it can help.",
                "The threads here are essentially a thread pool for scheduling operators, not for doing the math within each op (that's what intra_op threads do).",
                "In practice, most people leave it at 1 or 2 and focus on tuning intra_op_num_threads instead, since that's where the heavy compute actually happens.",
                "Default: 1 thread.",
            ],
            Self::EnableMemPattern => vec![
                "Enables memory pattern optimization to reduce memory allocation overhead.",
                "When enabled, ONNX Runtime pre-allocates memory based on the execution pattern.",
                "Reduces runtime memory allocation calls, improving performance.",
                "May increase initial memory usage slightly.",
                "Default: true (enabled).",
            ],
            Self::EnableCpuMemArena => vec![
                "Enables the CPU memory arena for more efficient memory management.",
                "Pre-allocates a memory pool to reduce allocation/deallocation overhead.",
                "Particularly beneficial for repeated inference calls.",
                "May increase baseline memory usage.",
                "Default: true (enabled).",
            ],
            Self::DeterministicCompute => vec![
                "Forces deterministic computation when possible.",
                "When enabled, the same inputs will always produce identical outputs.",
                "May disable some optimizations that introduce non-determinism.",
                "Useful for debugging and reproducibility testing.",
                "Default: false (disabled for better performance).",
            ],
            Self::OptimizedModelFilepath => vec![
                "Path to save the optimized model after graph optimizations.",
                "If set, ONNX Runtime writes the optimized graph to this file.",
                "Useful for inspecting what optimizations were applied.",
                "Can be loaded directly in future sessions to skip optimization.",
                "Leave empty to disable.",
            ],
            Self::EnableProfiling => vec![
                "Enables profiling to collect performance metrics.",
                "When enabled, generates a Chrome trace JSON file for analysis.",
                "Use Chrome's chrome://tracing to visualize the profile.",
                "Adds overhead during inference - disable for production.",
                "Default: false (disabled).",
            ],
            Self::ProfilingOutputPath => vec![
                "Path where profiling output will be written.",
                "Only used when enable_profiling is true.",
                "Output is in Chrome trace format (.json).",
                "Leave empty to use default location.",
            ],
            Self::LogId => vec![
                "Custom identifier for ONNX Runtime log messages.",
                "Helps distinguish logs from different sessions.",
                "Useful when running multiple ONNX sessions.",
                "Leave empty for default logging.",
            ],
            Self::LogLevel => vec![
                "Minimum severity level for ONNX Runtime log messages.",
                "Verbose: All messages including debug info.",
                "Info: Informational messages and above.",
                "Warning: Warnings and errors only.",
                "Error: Only error messages.",
                "Fatal: Only fatal errors.",
                "Default: Info.",
            ],
            Self::LogVerbosity => vec![
                "Verbosity level for verbose logging (0 or higher).",
                "Only applies when log_level is set to Verbose.",
                "Higher values produce more detailed output.",
                "Default: 0.",
            ],
            Self::UseEnvAllocators => vec![
                "Use environment-level allocators instead of session-specific ones.",
                "When enabled, memory allocators are shared across sessions.",
                "Can reduce memory fragmentation with multiple sessions.",
                "Default: false (each session has its own allocators).",
            ],
            Self::DenormalAsZero => vec![
                "Enables flush-to-zero and denormal-as-zero CPU modes.",
                "Treats very small floating-point numbers as zero.",
                "Can significantly speed up computation on some CPUs.",
                "May slightly reduce numerical precision for edge cases.",
                "Default: false (disabled).",
            ],
            Self::UseDeviceAllocatorForInitializers => vec![
                "Use device allocator when initializing model tensors.",
                "Can improve memory locality for GPU execution.",
                "For CPU-only inference, usually not needed.",
                "Default: false (disabled).",
            ],
            Self::AllowInterOpSpinning => vec![
                "Allow inter-op threads to spin briefly before blocking.",
                "Spinning can reduce latency for quick operations.",
                "Uses more CPU when threads are idle.",
                "Default: true (enabled).",
            ],
            Self::AllowIntraOpSpinning => vec![
                "Allow intra-op threads to spin briefly before blocking.",
                "Similar to inter-op spinning but for within-operator parallelism.",
                "Can reduce latency at the cost of CPU usage.",
                "Default: true (enabled).",
            ],
            Self::UsePrepacking => vec![
                "Enable prepacking optimizations for weights.",
                "Rearranges weight tensors for more efficient computation.",
                "Increases initialization time but improves inference speed.",
                "Default: true (enabled).",
            ],
            Self::IndependentThreadPool => vec![
                "Use an independent thread pool for this session.",
                "When enabled, session doesn't share threads with other sessions.",
                "Useful for isolating workloads or ensuring thread availability.",
                "Default: false (shares thread pool).",
            ],
            Self::NoEnvExecutionProviders => vec![
                "Don't inherit execution providers from the environment.",
                "When enabled, only explicitly added providers are used.",
                "Useful for controlling exactly which providers are active.",
                "Default: false (inherits environment providers).",
            ],
            Self::EnableQuantQdq => vec![
                "Enable Quantize/Dequantize (QDQ) fusion optimizations.",
                "Fuses quantization operations for better performance.",
                "Essential for running quantized models efficiently.",
                "Default: true (enabled).",
            ],
            Self::EnableDoubleQdqRemover => vec![
                "Enable the pass that removes redundant double QDQ nodes.",
                "Cleans up unnecessary quantize-dequantize pairs.",
                "Improves performance of quantized models.",
                "Default: true (enabled).",
            ],
            Self::EnableQdqCleanup => vec![
                "Remove QDQ nodes after processing completes.",
                "Final cleanup pass for quantization nodes.",
                "Usually not needed if other QDQ optimizations are enabled.",
                "Default: false (disabled).",
            ],
            Self::ApproximateGelu => vec![
                "Use approximate GELU activation instead of exact computation.",
                "GELU (Gaussian Error Linear Unit) is common in transformers.",
                "Approximation is faster with minimal accuracy loss.",
                "Default: false (uses exact GELU).",
            ],
            Self::EnableAotInlining => vec![
                "Enable ahead-of-time function inlining.",
                "Inlines function calls during graph optimization.",
                "Can improve performance by reducing call overhead.",
                "Default: true (enabled).",
            ],
            Self::DisabledOptimizers => vec![
                "List of optimizer names to disable.",
                "Comma-separated list of optimizer identifiers.",
                "Use when specific optimizations cause issues.",
                "Leave empty to enable all optimizers.",
            ],
            Self::ModelPath => vec![
                "Path to the ONNX model file.",
                "Supports .onnx format models.",
                "Can be absolute or relative to the working directory.",
                "Default: models/embedding_model.onnx",
            ],
            Self::EmbeddingDim => vec![
                "Dimension of the output embedding vectors.",
                "Must match the model's actual output dimension.",
                "Common values: 384 (MiniLM), 768 (BERT-base), 1024 (BERT-large).",
                "Default: 384.",
            ],
            Self::MaxLength => vec![
                "Maximum sequence length for input tokenization.",
                "Inputs longer than this are truncated.",
                "Must not exceed the model's maximum position embeddings.",
                "Default: 512 tokens.",
            ],
            Self::ExecutionOrder => vec![
                "Defines the order in which operators are scheduled for execution.",
                "TopologicalOrder (default): Operators execute in standard topological order, respecting data dependencies. This is optimal for most models.",
                "PriorityBased: Uses priority values to schedule operators — higher-priority ops may run before others even if graph topology allows either order.",
                "For embedding models and transformers, TopologicalOrder is always the right choice.",
            ],
            Self::CustomCreateThreadFn => vec![
                "Custom function for creating worker threads in the ONNX Runtime thread pool.",
                "Allows advanced users to override how threads are created, e.g., to set CPU affinity, scheduling priority, or custom stack sizes.",
                "Not configurable via this UI — requires code-level integration at session-creation time.",
                "If not set, ONNX Runtime creates threads using its platform default mechanism.",
            ],
            Self::CustomJoinThreadFn => vec![
                "Custom function for joining worker threads when the ONNX Runtime thread pool shuts down.",
                "Paired with custom_create_thread_fn to provide full lifecycle control over worker threads.",
                "Not configurable via this UI — requires code-level integration.",
                "If not set, uses ONNX Runtime's default thread join behavior.",
            ],
            Self::FreeDimensionOverrides => vec![
                "Override free (dynamic) dimensions in the ONNX model with fixed concrete values.",
                "Dynamic dimensions (marked '?' or named in the model graph) can be pinned to a fixed size at session creation, enabling shape-specific optimizations.",
                "Example: fixing batch_size=1 and sequence_length=128 allows the optimizer to fold constant shapes throughout the graph.",
                "Not configurable via this UI — requires code-level integration. Most embedding models already have fixed shapes.",
            ],
            Self::SessionConfigEntries => vec![
                "Key-value pairs for fine-grained ONNX Runtime session configuration beyond the standard API.",
                "Provides access to advanced settings using string keys like 'session.intra_op.allow_spinning' or 'session.dynamic_block_base'.",
                "The most commonly used session config keys are exposed as individual controls in the Session Config Keys panel on this page.",
                "Not configurable as raw key-value pairs via this UI — the exposed parameters cover the settings relevant to this deployment.",
            ],
            Self::SaveModelFormat => vec![
                "Format used when saving an optimized model to disk via optimized_model_filepath.",
                "ONNX (default): Standard ONNX protobuf format (.onnx). Compatible with all ONNX-capable tools and runtimes.",
                "ORT: ONNX Runtime flat-buffer format (.ort). Faster to load and smaller on disk, but only loadable by ONNX Runtime.",
                "Fixed to ONNX in this deployment.",
            ],
            Self::UseOrtModelBytesDirectly => vec![
                "When loading an ORT-format model, reference the raw model bytes in-place instead of copying them.",
                "Value 1: Zero-copy loading — the caller's model bytes buffer must remain valid for the entire session lifetime.",
                "Value 0 (default): ONNX Runtime copies the model bytes internally, so the caller's buffer can be freed after session creation.",
                "Not applicable for standard .onnx models. Fixed to 0 in this deployment.",
            ],
            Self::UseOrtModelBytesForInitializers => vec![
                "When loading an ORT-format model, also reference weight tensors (initializers) in-place from the model bytes buffer.",
                "Value 1: Initializer weights are memory-mapped directly from the buffer — zero additional allocation for weights.",
                "Value 0 (default): Initializers are copied into separately managed memory.",
                "Requires use_ort_model_bytes_directly=1 to also be set. Not applicable for .onnx models. Fixed to 0 here.",
            ],
            Self::IntraOpSpinControl => vec![
                "Fine-grained control over intra-op thread spinning, complementing allow_intra_op_spinning.",
                "Value 0 (default): Spinning behavior is governed entirely by the allow_intra_op_spinning session config key.",
                "Non-zero values are reserved for future ORT spin-control extensions.",
                "For standard spin tuning, use 'session.intra_op.allow_spinning' (exposed as 'session.intra_op.allow_spinning' above).",
            ],
            Self::DynamicBlockBase => vec![
                "Base block size for dynamic parallelism scheduling in the intra-op thread pool.",
                "Controls how work items are chunked when distributing a parallel operation across threads.",
                "Value 0 (default): ONNX Runtime automatically determines the block size based on workload.",
                "Advanced tuning only — the default is optimal for the vast majority of models.",
            ],
            Self::GraphOptimizationsLoopLevel => vec![
                "Number of passes to run the full graph optimization pipeline.",
                "Some optimizations expose new opportunities for other passes — running multiple loops can find additional savings.",
                "Value 0 (default): Run each optimization pass once.",
                "Higher values increase session initialization time. Rarely beneficial beyond 1-2 extra loops.",
            ],
            Self::EnableBiasGeluFusion => vec![
                "Fuse Bias + GELU activation patterns into a single optimized kernel.",
                "BiasGELU is ubiquitous in transformer feed-forward layers: a linear projection adds a bias vector, then applies GELU.",
                "Fusing the two eliminates a memory round-trip between the bias add and the GELU — the activation is computed in the same pass.",
                "Value 1 (default): Fusion enabled. Part of the Extended optimization level.",
            ],
            Self::EnableConvBnFusion => vec![
                "Absorb Batch Normalization parameters into the preceding Convolution layer.",
                "During inference, BatchNorm uses fixed statistics (mean, variance, scale, bias). These can be folded into the Conv weights and bias, eliminating the BN operator entirely.",
                "Reduces operator count, memory bandwidth, and latency — especially significant in CNN-based models.",
                "Value 1 (default): Fusion enabled. Part of the Basic optimization level. Has no effect for pure transformer models.",
            ],
            Self::RunTag => vec![
                "Optional string tag attached to a specific inference run, visible in profiling output.",
                "When profiling is enabled, the run_tag appears in the Chrome trace JSON alongside timing data, making it easy to distinguish runs over multiple inputs.",
                "Not set in this deployment — profiling output uses default run identifiers.",
                "Useful in custom instrumentation scenarios where many inference calls are profiled simultaneously.",
            ],
            Self::RunLogSeverityLevel => vec![
                "Per-run override for log severity, applied only to a single inference call.",
                "When set, overrides the session-level log_severity_level for this specific run only.",
                "Inherits from the session setting by default — no per-run override is active.",
                "Useful for temporarily raising logging on suspicious inputs without changing global session settings.",
            ],
            Self::RunLogVerbosityLevel => vec![
                "Per-run override for log verbosity, applied only to a single inference call.",
                "When set, overrides the session-level log_verbosity_level for this specific run.",
                "Inherits from the session setting by default — no per-run override is active.",
            ],
            Self::LogTag => vec![
                "String tag prepended to all log messages emitted during this inference run.",
                "Helps correlate log output with specific requests when multiple concurrent inference calls share the same log stream.",
                "Not set — log messages use the session log_id as the identifier.",
                "Most useful in high-throughput services where many requests are in-flight simultaneously.",
            ],
            Self::EpIntraOpNumThreads => vec![
                "Thread count hint passed directly to the CPU Execution Provider for intra-operator parallelism.",
                "This is a lower-level override applied at the EP level, below the session-level intra_op_num_threads setting.",
                "Value 0 (auto): The CPU EP defers to the session-level intra_op_num_threads setting.",
                "In almost all cases, configure threads at the session level (Session Options > Threading) rather than here.",
            ],
            Self::EpInterOpNumThreads => vec![
                "Thread count hint passed directly to the CPU Execution Provider for inter-operator parallelism.",
                "Value 0 (auto): The CPU EP defers to the session-level inter_op_num_threads setting.",
                "Setting a non-zero value overrides the session-level setting specifically for CPU execution.",
                "Configure at the session level unless you have a compelling reason to override per-EP.",
            ],
            Self::UseArena => vec![
                "Enable the memory arena allocator in the CPU Execution Provider.",
                "The arena pre-allocates a large contiguous block and suballocates from it, replacing many small malloc calls with pointer arithmetic.",
                "Default: true — strongly recommended for inference workloads that perform repeated tensor allocations.",
                "Corresponds to the session-level enable_cpu_mem_arena option but applied directly at the EP level.",
            ],
            Self::ArenaExtendStrategy => vec![
                "Strategy used to grow the CPU memory arena when its current capacity is exhausted.",
                "kNextPowerOfTwo (default): Doubles the arena size on each extension. Amortizes reallocation cost — fewer total extensions, larger peak reservation.",
                "kSameAsRequested: Extends by exactly the amount requested. Lower peak memory but more frequent extensions under varied allocation sizes.",
                "kNextPowerOfTwo is the standard choice for inference workloads with unpredictable allocation sizes.",
            ],
            Self::InitialChunkSizeBytes => vec![
                "Size of the first memory chunk allocated when the CPU arena is created.",
                "Value 0 (default): ONNX Runtime chooses an appropriate initial size based on heuristics.",
                "Setting a custom value (e.g., 67108864 for 64 MB) reduces early reallocation if you know your model's rough memory footprint.",
                "Powers of 2 work best with the arena's growth strategy. Only tune if profiling shows excessive early reallocation.",
            ],
            Self::MaxChunkSizeBytes => vec![
                "Maximum size of any single memory chunk within the CPU arena.",
                "Value 0 (default): No cap — chunks can grow as large as a single allocation requires.",
                "Capping chunk size limits the largest contiguous allocation, which can reduce address-space fragmentation on long-running services.",
                "Expressed in bytes. Set to 0 unless you observe memory fragmentation issues.",
            ],
            Self::InitialGrowthChunkSizeBytes => vec![
                "Size of the first growth chunk when the arena needs to expand beyond its initial allocation.",
                "Value 0 (default): ONNX Runtime determines the growth chunk size automatically, typically matching the initial chunk size.",
                "Tuning this can smooth the arena's growth curve for models with predictable but non-uniform allocation patterns.",
                "Expressed in bytes. Leave at 0 unless you have profiling data showing arena thrash.",
            ],
            Self::MaxDeadBytesPerChunk => vec![
                "Maximum bytes of 'dead' memory — allocated but no longer referenced — tolerated within a single arena chunk before it is released.",
                "Value 0 (default): No limit. Chunks are never freed by the arena even if they become mostly empty.",
                "Setting a non-zero limit allows the arena to compact and release chunks that have fragmented, reducing memory waste.",
                "Reduces long-term memory footprint at the cost of occasional reallocation. Useful for long-running services with variable model inputs.",
            ],
        }
    }
}
