#!/bin/bash
# scripts/custom_model.sh
# Version: 1.0.0
# 
# Custom model installation for Agentic RAG
# Imports a fine-tuned GGUF model into Ollama
#
# Usage:
#   CUSTOM_MODEL_PATH=/path/to/model.gguf ./custom_model.sh
#   CUSTOM_MODEL_URL=https://... ./custom_model.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODEL_DIR="${HOME}/.local/share/ag/models"
MODEL_NAME="${CUSTOM_MODEL_NAME:-ag-custom}"
CONFIG_DIR="${HOME}/.config/ag"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Check if Ollama is running
check_ollama() {
    log_step "Checking Ollama status..."
    
    if ! command -v ollama &> /dev/null; then
        log_error "Ollama is not installed. Install from: https://ollama.ai"
        exit 1
    fi
    
    if ! curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
        log_warn "Ollama is not running. Attempting to start..."
        
        # Try to start Ollama
        if command -v systemctl &> /dev/null; then
            sudo systemctl start ollama 2>/dev/null || true
        else
            ollama serve &>/dev/null &
        fi
        
        # Wait for Ollama to start
        for i in {1..10}; do
            if curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
                log_info "Ollama started successfully"
                return 0
            fi
            sleep 1
        done
        
        log_error "Failed to start Ollama. Start manually with: ollama serve"
        exit 1
    fi
    
    log_info "Ollama is running"
}

# Download custom model GGUF
download_model() {
    local url="$1"
    local output="$2"
    local expected_hash="$3"

    log_step "Downloading custom model..."
    log_info "URL: $url"
    log_info "Output: $output"
    
    mkdir -p "$(dirname "$output")"
    
    if command -v wget &> /dev/null; then
        wget -q --show-progress -O "$output" "$url"
    elif command -v curl &> /dev/null; then
        curl -L --progress-bar -o "$output" "$url"
    else
        log_error "Neither wget nor curl available"
        exit 1
    fi

    # Verify hash if provided
    if [ -n "$expected_hash" ]; then
        log_step "Verifying file hash..."
        local actual_hash=$(sha256sum "$output" | cut -d' ' -f1)
        if [ "$actual_hash" != "$expected_hash" ]; then
            log_error "Hash mismatch!"
            log_error "Expected: $expected_hash"
            log_error "Got: $actual_hash"
            rm -f "$output"
            exit 1
        fi
        log_info "Hash verified ✓"
    fi
    
    log_info "Download complete"
}

# Create Modelfile and import to Ollama
import_to_ollama() {
    local gguf_path="$1"
    local model_name="$2"

    log_step "Creating Modelfile..."
    
    mkdir -p "$MODEL_DIR"
    
    # Copy GGUF to model directory
    local gguf_filename=$(basename "$gguf_path")
    local target_path="${MODEL_DIR}/${gguf_filename}"
    
    if [ "$gguf_path" != "$target_path" ]; then
        cp "$gguf_path" "$target_path"
    fi

    # Create Modelfile
    cat > "${MODEL_DIR}/Modelfile" << EOF
FROM ./${gguf_filename}

TEMPLATE """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{{ .Prompt }}

### Input:
{{ .Context }}

### Response:
"""

PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER stop "### Instruction:"
PARAMETER stop "### Input:"
PARAMETER stop "### Response:"
EOF

    log_step "Importing model to Ollama..."
    cd "$MODEL_DIR"
    
    if ollama create "$model_name" -f Modelfile; then
        log_info "Model '$model_name' imported successfully!"
    else
        log_error "Failed to import model"
        exit 1
    fi
}

# Check if model already exists
check_existing() {
    if ollama list 2>/dev/null | grep -q "^${MODEL_NAME}"; then
        log_warn "Model '$MODEL_NAME' already exists in Ollama"
        read -p "Overwrite? [y/N] " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Skipping model import"
            exit 0
        fi
        
        # Remove existing model
        log_step "Removing existing model..."
        ollama rm "$MODEL_NAME" 2>/dev/null || true
    fi
}

# Update configuration
update_config() {
    log_step "Updating configuration..."
    
    mkdir -p "$CONFIG_DIR"
    
    # Create or update env file
    local env_file="${CONFIG_DIR}/custom_model.env"
    
    cat > "$env_file" << EOF
# Custom Model Configuration
# Generated by custom_model.sh on $(date)

CUSTOM_MODEL_ENABLED=true
CUSTOM_MODEL_NAME=${MODEL_NAME}
CUSTOM_MODEL_FALLBACK=true
EOF

    log_info "Configuration saved to: $env_file"
    log_info "Source this file or add to your environment:"
    log_info "  source $env_file"
}

# Show usage
show_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Import a custom fine-tuned model into Ollama for use with Agentic RAG."
    echo ""
    echo "Options:"
    echo "  -h, --help              Show this help message"
    echo "  -p, --path PATH         Path to local GGUF file"
    echo "  -u, --url URL           URL to download GGUF file"
    echo "  -n, --name NAME         Model name in Ollama (default: ag-custom)"
    echo "  -H, --hash HASH         Expected SHA256 hash for verification"
    echo ""
    echo "Environment variables:"
    echo "  CUSTOM_MODEL_PATH       Path to local GGUF file"
    echo "  CUSTOM_MODEL_URL        URL to download GGUF file"
    echo "  CUSTOM_MODEL_NAME       Model name in Ollama"
    echo "  CUSTOM_MODEL_HASH       Expected SHA256 hash"
    echo ""
    echo "Examples:"
    echo "  # Import from local file"
    echo "  $0 --path /path/to/model.gguf"
    echo ""
    echo "  # Download and import"
    echo "  $0 --url https://example.com/model.gguf"
    echo ""
    echo "  # Using environment variables"
    echo "  CUSTOM_MODEL_PATH=/path/to/model.gguf $0"
}

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                show_usage
                exit 0
                ;;
            -p|--path)
                CUSTOM_MODEL_PATH="$2"
                shift 2
                ;;
            -u|--url)
                CUSTOM_MODEL_URL="$2"
                shift 2
                ;;
            -n|--name)
                MODEL_NAME="$2"
                shift 2
                ;;
            -H|--hash)
                CUSTOM_MODEL_HASH="$2"
                shift 2
                ;;
            *)
                log_error "Unknown option: $1"
                show_usage
                exit 1
                ;;
        esac
    done
}

# Main
main() {
    parse_args "$@"
    
    local gguf_url="${CUSTOM_MODEL_URL:-}"
    local gguf_path="${CUSTOM_MODEL_PATH:-}"
    local expected_hash="${CUSTOM_MODEL_HASH:-}"

    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║           Agentic RAG Custom Model Installer                 ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""

    check_ollama
    check_existing

    if [ -n "$gguf_path" ] && [ -f "$gguf_path" ]; then
        log_info "Using local GGUF: $gguf_path"
        import_to_ollama "$gguf_path" "$MODEL_NAME"
    elif [ -n "$gguf_url" ]; then
        local output="${MODEL_DIR}/${MODEL_NAME}.gguf"
        download_model "$gguf_url" "$output" "$expected_hash"
        import_to_ollama "$output" "$MODEL_NAME"
    else
        log_error "No model source specified"
        echo ""
        echo "Please provide either:"
        echo "  --path /path/to/model.gguf"
        echo "  --url https://example.com/model.gguf"
        echo ""
        echo "Or set environment variables:"
        echo "  CUSTOM_MODEL_PATH=/path/to/model.gguf"
        echo "  CUSTOM_MODEL_URL=https://..."
        echo ""
        show_usage
        exit 1
    fi

    update_config

    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                    Setup Complete! ✓                         ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    log_info "Custom model '$MODEL_NAME' is ready!"
    echo ""
    echo "Test with:"
    echo "  ollama run $MODEL_NAME \"Hello, how are you?\""
    echo ""
    echo "Enable in Agentic RAG:"
    echo "  export CUSTOM_MODEL_ENABLED=true"
    echo "  export CUSTOM_MODEL_NAME=$MODEL_NAME"
    echo ""
}

main "$@"
